// const brand = ('../testdir')
const path = require('path');
module.exports.workPath = path.resolve("./assets");
module.exports.domain = ("domain.ru/chasy/");
module.exports.headingsFile = path.resolve('./heading_test.txt');
module.exports.introText = path.resolve('./random-text.txt');
module.exports.copyFile = path.resolve('./copy-text.txt');
module.exports.priceMin = (218);
module.exports.priceMax = (398);
module.exports.prodidAdd = (2);
module.exports.priceAdd = (-300);
