// const brand = ('../testdir')
const path = require('path');
module.exports.brand = path.resolve("./testdir");
module.exports.headingsFile = path.resolve('./heading_test.txt');
module.exports.introText = path.resolve('./random-text.txt');
module.exports.copyFile = path.resolve('./copy-text.txt');
module.exports.priceMin = (218);
module.exports.priceMax = (398);
module.exports.prodidAdd = (2);
module.exports.priceAdd = (-300);
